defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/openjdk:8-jdk

persist: &persist
  persist_to_workspace:
    root: .
    paths:
      - .

attach: &attach
  attach_workspace:
    at: ~/workspace

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Compile
          command: mvn compile
      - <<: *persist
  test:
    <<: *defaults
    steps:
      - <<: *attach
      - run:
          name: Running tests
          command: mvn test
      - <<: *persist
  report:
    <<: *defaults
    steps:
      - <<: *attach
      - run:
          name: Prepare for Codecov command
          command: |
            sudo apt-get install python-pip
            sudo pip install codecov
      - run:
          name: Report coverage
          command: codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - report:
          requires:
            - test
          filters:
            branches:
              only: develop