defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/openjdk:8-jdk

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Compile
          command: mvn compile
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Running tests
          command: mvn test
      - persist_to_workspace:
          root: .
          paths:
            - .
  report:
    <<: *defaults
    steps:
       - attach_workspace:
           at: ~/workspace
       - run:
           name: Prepare for Codecov command
           command: |
             sudo apt-get install python-pip
             sudo pip install codecov
       - run:
           name: Report coverage
           command: codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - report:
          requires:
            - test
          filters:
            branches:
              only: master